"""
Event-Driven Wiki Publisher
===========================
Replaces the "full rebuild every 12h" approach with a targeted publisher
that only regenerates HTML pages whose underlying entity data has changed.

A page is rebuilt when:
  - entity["dirty"] is True   (mention_count changed, new facts added, or
                                entity was newly created)

After publishing, the flag is cleared: entity["dirty"] = False.

The publisher still updates articles.html, index.html stats, and sitemap
on every run (DB-48) regardless of which pages changed — those three files
are always rebuilt because their stats may change even if individual
article content is the same.

Rules respected:
  DB-40 / DB-44 : Only creates/edits pages this agent created itself.
  DB-41         : New pages use the exact current page layout.
  DB-47         : No "sam-" prefix in URL slugs.
  DB-48         : Always updates articles.html + index.html + sitemap.
"""

from __future__ import annotations

import os
import re
import json
from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Slug helper
# ---------------------------------------------------------------------------

def _slugify(name: str) -> str:
    """Return a URL-safe slug (DB-47: no 'sam-' prefix)."""
    slug = re.sub(r"[^\w\s-]", "", name.lower()).strip()
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    # DB-47: never start with 'sam-'
    if slug.startswith("sam-"):
        slug = slug[4:]
    return slug


# ---------------------------------------------------------------------------
# HTML template helpers
# ---------------------------------------------------------------------------

def _build_article_html(entity: dict[str, Any]) -> str:
    """
    Build a static HTML article page from entity data.
    Matches the exact _article-template.html structure.
    """
    name = entity.get("name", "Unknown")
    score = entity.get("score", 0)
    rank = entity.get("rank", "?")
    mention_count = entity.get("mention_count", 0)
    facts = entity.get("all_facts", [])
    facts_html = "\n".join(f"<li>{_html_escape(f)}</li>" for f in facts) if facts else "<li>No facts recorded yet.</li>"

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_html_escape(name)} — SAM Wiki</title>
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <header>
    <nav><a href="/index.html">Home</a> &rsaquo; <a href="/wiki/articles.html">Articles</a> &rsaquo; {_html_escape(name)}</nav>
  </header>
  <main class="article">
    <h1>{_html_escape(name)}</h1>
    <p class="meta">Rank: #{rank} &middot; Score: {score:.2f} &middot; Mentions: {mention_count}</p>
    <section>
      <h2>Known Facts</h2>
      <ul>
        {facts_html}
      </ul>
    </section>
  </main>
  <footer>
    <p>Auto-generated by SAM v2 Intelligence &middot; {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p>
  </footer>
</body>
</html>"""


def _html_escape(text: str) -> str:
    """Minimal HTML escaping."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ---------------------------------------------------------------------------
# Publisher
# ---------------------------------------------------------------------------

class WikiPublisher:
    """
    Event-driven wiki publisher.  Only rebuilds pages flagged as dirty.
    """

    def __init__(self, wiki_output_dir: str = "wiki", base_url: str = ""):
        self.wiki_output_dir = wiki_output_dir
        # Allow override via constructor; falls back to env var then default.
        self.base_url = (
            base_url
            or os.environ.get("WIKI_BASE_URL", "https://crypto-moonboys.github.io/wiki")
        )

    def publish(self, memory: dict[str, Any]) -> dict[str, Any]:
        """
        Inspect all entities, rebuild only dirty ones, then update the
        three global registry files (DB-48).

        Returns a summary dict describing what was published.
        """
        os.makedirs(self.wiki_output_dir, exist_ok=True)

        entities = memory.get("entities", {})
        rebuilt: list[str] = []
        skipped: list[str] = []

        for name, entity in entities.items():
            if entity.get("dirty", False):
                self._write_article(entity)
                entity["dirty"] = False
                rebuilt.append(name)
            else:
                skipped.append(name)

        # DB-48: always update registry files
        self._update_articles_registry(entities)
        self._update_index_stats(entities)
        self._update_sitemap(entities)

        return {
            "rebuilt": rebuilt,
            "skipped": skipped,
            "total_entities": len(entities),
            "published_at": datetime.now(timezone.utc).isoformat(),
        }

    # ------------------------------------------------------------------
    # Per-article writing
    # ------------------------------------------------------------------

    def _write_article(self, entity: dict[str, Any]) -> None:
        slug = _slugify(entity["name"])
        path = os.path.join(self.wiki_output_dir, f"{slug}.html")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(_build_article_html(entity))

    # ------------------------------------------------------------------
    # DB-48 registry files
    # ------------------------------------------------------------------

    def _update_articles_registry(self, entities: dict[str, Any]) -> None:
        rows = "\n".join(
            f'  <li><a href="{_slugify(e["name"])}.html">{_html_escape(e["name"])}</a>'
            f" — score {e.get('score', 0):.2f}</li>"
            for e in sorted(entities.values(), key=lambda x: x.get("rank", 9999))
        )
        html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Articles — SAM Wiki</title>
  <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  <header><nav><a href="/index.html">Home</a> &rsaquo; Articles</nav></header>
  <main>
    <h1>All Articles</h1>
    <ul>
{rows}
    </ul>
  </main>
  <footer><p>Updated {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p></footer>
</body>
</html>"""
        with open(os.path.join(self.wiki_output_dir, "articles.html"), "w", encoding="utf-8") as fh:
            fh.write(html)

    def _update_index_stats(self, entities: dict[str, Any]) -> None:
        total = len(entities)
        avg_score = (
            sum(e.get("score", 0) for e in entities.values()) / total
            if total else 0
        )
        stats = {
            "total_entities": total,
            "average_score": round(avg_score, 2),
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }
        stats_path = os.path.join(self.wiki_output_dir, "index_stats.json")
        with open(stats_path, "w", encoding="utf-8") as fh:
            json.dump(stats, fh, indent=2)

    def _update_sitemap(self, entities: dict[str, Any]) -> None:
        base_url = self.base_url
        urls = [f"{base_url}/articles.html"]
        for name in entities:
            urls.append(f"{base_url}/{_slugify(name)}.html")
        entries = "\n".join(
            f"  <url><loc>{u}</loc><changefreq>daily</changefreq></url>"
            for u in urls
        )
        sitemap = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>"""
        with open(os.path.join(self.wiki_output_dir, "sitemap.xml"), "w", encoding="utf-8") as fh:
            fh.write(sitemap)
